spring:
  application:
    name: ProductService

  datasource:
    url: jdbc:mysql://localhost:3306/myApplication
    username: root
    password: Shanthi@2709
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
jwt:
  secret: mySuperSecretKeyForJwtGeneration123456
  expiration: 3600000 # 1 hour



